
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 09 17:17:35 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 21;
  public static final int LBRACKET = 9;
  public static final int CHAR = 44;
  public static final int CONST = 5;
  public static final int LPAREN = 13;
  public static final int SEMI = 8;
  public static final int CONTINUE = 30;
  public static final int MINUS = 23;
  public static final int RPAREN = 14;
  public static final int AND = 37;
  public static final int LT = 20;
  public static final int OR = 36;
  public static final int BOOL = 45;
  public static final int COMMA = 6;
  public static final int CLASS = 11;
  public static final int INC = 41;
  public static final int DIV = 26;
  public static final int NUM = 46;
  public static final int PLUS = 22;
  public static final int ASSIGN = 7;
  public static final int IF = 27;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int RETURN = 31;
  public static final int RBRACKET = 10;
  public static final int NEW = 38;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int MOD = 25;
  public static final int NEQ = 17;
  public static final int IDENT = 43;
  public static final int BREAK = 29;
  public static final int VOID = 15;
  public static final int EQ = 16;
  public static final int GTE = 19;
  public static final int ARROW = 39;
  public static final int FOREACH = 35;
  public static final int LBRACE = 3;
  public static final int ELSE = 28;
  public static final int READ = 32;
  public static final int WHILE = 40;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 12;
  public static final int PROG = 2;
  public static final int DEC = 42;
  public static final int GT = 18;
  public static final int PRINT = 33;
}

